# Generated by Django 3.2.5 on 2021-07-22 13:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0005_productmodel_real_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='wishlist',
            field=models.ManyToManyField(related_name='wishlist', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
