# Generated by Django 3.2.6 on 2021-08-18 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20210818_2327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='size',
        ),
        migrations.DeleteModel(
            name='SizeModel',
        ),
    ]
