# Generated by Django 3.2.6 on 2021-08-18 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20210819_0000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colormodel',
            name='code',
        ),
        migrations.AddField(
            model_name='colormodel',
            name='title',
            field=models.CharField(max_length=25, null=True, verbose_name='title'),
        ),
    ]
